network:
    version: 2
        renderer: networkd
        ethernets:
            ens18:
                dhcp4: false
                optional: true
            ens19:
                dhcp4: false
                optional: true