network:
    version: 2
        renderer: networkd
        ethernets:
            {{ interface1 }}:
                dhcp4: false
                optional: true
            {{ interface2 }}:
                dhcp4: false
                optional: true