network:
    version: 2
    renderer: networkd
    bonds:
        bond0:
            interfaces: [{{ interface1 }}, {{ interface2 }}]
            addresses: [{{ ip }}/{{ mask }}]
            gateway4: {{ gateway }}
            parameters:
                mode: 802.3ad
            nameservers:
                addresses: [{{ dns1 }}, {{ dns2 }}]
            dhcp4: false
            optional: true