network:
    version: 2
    renderer: networkd
    bonds:
        bond0:
            interfaces: [ens18, ens19]
            addresses: [192.168.2.2/22]
            gateway4: 192.168.0.1
            parameters:
                mode: 802.3ad
            nameservers:
                addresses: [1.1.1.1, 4.4.4.4, 8.8.8.8]
            dhcp4: false
            optional: true