---
- name: change user password
  user:
    name: ubuntu
    update_password: always
    password: "{{ new_user_password }}"


- name: Create new user
  user:
    name: "{{ new_seconduser_name }}"
    password: "{{ new_seconduser_pass }}"
    update_password: on_create
    shell: /bin/bash
    createhome: yes